### ISSUE TITLE
打开文件是好像少了编码

### ISSUE THREAD

**Issue by OliverChao** [mouday/chinesename#4]
出现了编码问题：
'gbk' codec can't decode byte 0x80 in position 2: illegal multibyte sequence
是不是打开文件的时候少了编码转换

**Comment by mouday** [comment]
文件头上有编码声明的，应该没问题，你试试python3，我之前2和3都试过的，都没问题

**Comment by OliverChao** [comment]
![image](https://user-images.githubusercontent.com/39361033/43044782-79a5bfce-8ddf-11e8-9075-9960d07313ad.png)

**Comment by OliverChao** [comment]
我用的就是python3，，应该时读取文件的时候出现的编码问题 'gbk' codec can't decode byte 0x80 in position 2: illegal multibyte sequence

**Comment by mouday** [comment]
我在windows上试，发现也有同样的问题，已经更新了一个版本`chinesename 0.0.9` 

更新一下试试看:
```
pip install -U chinesename -i https://pypi.python.org/simple
```
